// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appeals.sql

package sqlcdb

import (
	"context"
	"time"
)

const forgetAppealSignatures = `-- name: ForgetAppealSignatures :exec
DELETE FROM appeal_signatures WHERE user_id = $1
`

func (q *Queries) ForgetAppealSignatures(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, forgetAppealSignatures, userID)
	return err
}

const listAppealSignatures = `-- name: ListAppealSignatures :many
SELECT issue_id::text AS issue_id, user_id, full_name, apartment, signed_at
FROM appeal_signatures
WHERE issue_id = $1
ORDER BY signed_at, user_id
`

type ListAppealSignaturesRow struct {
	IssueID   string
	UserID    int64
	FullName  string
	Apartment string
	SignedAt  time.Time
}

func (q *Queries) ListAppealSignatures(ctx context.Context, issueID string) ([]ListAppealSignaturesRow, error) {
	rows, err := q.db.Query(ctx, listAppealSignatures, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppealSignaturesRow
	for rows.Next() {
		var i ListAppealSignaturesRow
		if err := rows.Scan(
			&i.IssueID,
			&i.UserID,
			&i.FullName,
			&i.Apartment,
			&i.SignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signAppeal = `-- name: SignAppeal :exec
INSERT INTO appeal_signatures (issue_id, user_id, full_name, apartment, signed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (issue_id, user_id) DO UPDATE SET
    full_name = EXCLUDED.full_name, apartment = EXCLUDED.apartment, signed_at = EXCLUDED.signed_at
`

type SignAppealParams struct {
	IssueID   string
	UserID    int64
	FullName  string
	Apartment string
	SignedAt  time.Time
}

// Повторная подпись обновляет ФИО и квартиру: житель мог сначала подписать без них.
func (q *Queries) SignAppeal(ctx context.Context, arg SignAppealParams) error {
	_, err := q.db.Exec(ctx, signAppeal,
		arg.IssueID,
		arg.UserID,
		arg.FullName,
		arg.Apartment,
		arg.SignedAt,
	)
	return err
}

const withdrawAppeal = `-- name: WithdrawAppeal :exec
DELETE FROM appeal_signatures WHERE issue_id = $1 AND user_id = $2
`

type WithdrawAppealParams struct {
	IssueID string
	UserID  int64
}

func (q *Queries) WithdrawAppeal(ctx context.Context, arg WithdrawAppealParams) error {
	_, err := q.db.Exec(ctx, withdrawAppeal, arg.IssueID, arg.UserID)
	return err
}
