// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot.sql

package sqlcdb

import (
	"context"
	"time"
)

const setBotPending = `-- name: SetBotPending :exec
INSERT INTO bot_pending (user_id, action, ref, text, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    action = EXCLUDED.action, ref = EXCLUDED.ref, text = EXCLUDED.text, expires_at = EXCLUDED.expires_at
`

type SetBotPendingParams struct {
	UserID    int64
	Action    string
	Ref       string
	Text      string
	ExpiresAt time.Time
}

func (q *Queries) SetBotPending(ctx context.Context, arg SetBotPendingParams) error {
	_, err := q.db.Exec(ctx, setBotPending,
		arg.UserID,
		arg.Action,
		arg.Ref,
		arg.Text,
		arg.ExpiresAt,
	)
	return err
}

const takeBotPending = `-- name: TakeBotPending :one
DELETE FROM bot_pending WHERE user_id = $1
RETURNING action, ref, text, expires_at
`

type TakeBotPendingRow struct {
	Action    string
	Ref       string
	Text      string
	ExpiresAt time.Time
}

// Забираем и стираем сразу: истёкшее действие тоже удаляется, срок проверяет репозиторий.
func (q *Queries) TakeBotPending(ctx context.Context, userID int64) (TakeBotPendingRow, error) {
	row := q.db.QueryRow(ctx, takeBotPending, userID)
	var i TakeBotPendingRow
	err := row.Scan(
		&i.Action,
		&i.Ref,
		&i.Text,
		&i.ExpiresAt,
	)
	return i, err
}
