// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: council.sql

package sqlcdb

import (
	"context"
	"time"
)

const getPoll = `-- name: GetPoll :one
SELECT id, house_id, proposal_id, question, options, created_at, closes_at FROM polls WHERE id = $1
`

func (q *Queries) GetPoll(ctx context.Context, id string) (Poll, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.ProposalID,
		&i.Question,
		&i.Options,
		&i.CreatedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, house_id, author_id, text, status, answer, created_at, answered_at FROM proposals WHERE id = $1
`

func (q *Queries) GetProposal(ctx context.Context, id string) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.AuthorID,
		&i.Text,
		&i.Status,
		&i.Answer,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const insertPoll = `-- name: InsertPoll :exec
INSERT INTO polls (id, house_id, proposal_id, question, options, created_at, closes_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPollParams struct {
	ID         string
	HouseID    string
	ProposalID *string
	Question   string
	Options    []string
	CreatedAt  time.Time
	ClosesAt   time.Time
}

func (q *Queries) InsertPoll(ctx context.Context, arg InsertPollParams) error {
	_, err := q.db.Exec(ctx, insertPoll,
		arg.ID,
		arg.HouseID,
		arg.ProposalID,
		arg.Question,
		arg.Options,
		arg.CreatedAt,
		arg.ClosesAt,
	)
	return err
}

const insertProposal = `-- name: InsertProposal :exec
INSERT INTO proposals (id, house_id, author_id, text, status, answer, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertProposalParams struct {
	ID        string
	HouseID   string
	AuthorID  int64
	Text      string
	Status    string
	Answer    string
	CreatedAt time.Time
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) error {
	_, err := q.db.Exec(ctx, insertProposal,
		arg.ID,
		arg.HouseID,
		arg.AuthorID,
		arg.Text,
		arg.Status,
		arg.Answer,
		arg.CreatedAt,
	)
	return err
}

const insertVote = `-- name: InsertVote :execrows
INSERT INTO poll_votes (poll_id, user_id, option) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertVoteParams struct {
	PollID string
	UserID int64
	Option int32
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVote, arg.PollID, arg.UserID, arg.Option)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuthorProposals = `-- name: ListAuthorProposals :many
SELECT id, house_id, author_id, text, status, answer, created_at, answered_at FROM proposals WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuthorProposalsParams struct {
	AuthorID int64
	MaxRows  int32
}

func (q *Queries) ListAuthorProposals(ctx context.Context, arg ListAuthorProposalsParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listAuthorProposals, arg.AuthorID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.AuthorID,
			&i.Text,
			&i.Status,
			&i.Answer,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousePolls = `-- name: ListHousePolls :many
SELECT id, house_id, proposal_id, question, options, created_at, closes_at FROM polls WHERE house_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListHousePollsParams struct {
	HouseID string
	MaxRows int32
}

func (q *Queries) ListHousePolls(ctx context.Context, arg ListHousePollsParams) ([]Poll, error) {
	rows, err := q.db.Query(ctx, listHousePolls, arg.HouseID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Poll
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.ProposalID,
			&i.Question,
			&i.Options,
			&i.CreatedAt,
			&i.ClosesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseProposals = `-- name: ListHouseProposals :many
SELECT id, house_id, author_id, text, status, answer, created_at, answered_at FROM proposals WHERE house_id = $1
ORDER BY (status = 'new') DESC, created_at DESC
LIMIT $2
`

type ListHouseProposalsParams struct {
	HouseID string
	MaxRows int32
}

// Папка председателя: новые первыми, дальше по дате.
func (q *Queries) ListHouseProposals(ctx context.Context, arg ListHouseProposalsParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listHouseProposals, arg.HouseID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.AuthorID,
			&i.Text,
			&i.Status,
			&i.Answer,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollTally = `-- name: PollTally :many
SELECT option, count(*)::int AS votes, bool_or(user_id = $1)::bool AS mine
FROM poll_votes WHERE poll_id = $2
GROUP BY option
`

type PollTallyParams struct {
	UserID int64
	PollID string
}

type PollTallyRow struct {
	Option int32
	Votes  int32
	Mine   bool
}

func (q *Queries) PollTally(ctx context.Context, arg PollTallyParams) ([]PollTallyRow, error) {
	rows, err := q.db.Query(ctx, pollTally, arg.UserID, arg.PollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollTallyRow
	for rows.Next() {
		var i PollTallyRow
		if err := rows.Scan(&i.Option, &i.Votes, &i.Mine); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyProposal = `-- name: ReplyProposal :execrows
UPDATE proposals SET status = $1, answer = $2, answered_at = $3
WHERE id = $4 AND status = 'new'
`

type ReplyProposalParams struct {
	Status     string
	Answer     string
	AnsweredAt *time.Time
	ID         string
}

// Ответ один: второй председатель (или повторное нажатие) не перезапишет первый.
func (q *Queries) ReplyProposal(ctx context.Context, arg ReplyProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, replyProposal,
		arg.Status,
		arg.Answer,
		arg.AnsweredAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
