// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: houses.sql

package sqlcdb

import (
	"context"
)

const getHouse = `-- name: GetHouse :one
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses WHERE id = $1
`

func (q *Queries) GetHouse(ctx context.Context, id string) (House, error) {
	row := q.db.QueryRow(ctx, getHouse, id)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.District,
		&i.YearBuilt,
		&i.Floors,
		&i.EntrancesCount,
		&i.OrganizationID,
		&i.Lat,
		&i.Lon,
		&i.Source,
	)
	return i, err
}

const getObjectByCode = `-- name: GetObjectByCode :one
SELECT id, house_id, COALESCE(entrance_id, '')::text AS entrance_id, category, label, qr_code
FROM asset_objects
WHERE qr_code = $1
`

type GetObjectByCodeRow struct {
	ID         string
	HouseID    string
	EntranceID string
	Category   string
	Label      string
	QrCode     string
}

func (q *Queries) GetObjectByCode(ctx context.Context, qrCode string) (GetObjectByCodeRow, error) {
	row := q.db.QueryRow(ctx, getObjectByCode, qrCode)
	var i GetObjectByCodeRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.EntranceID,
		&i.Category,
		&i.Label,
		&i.QrCode,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, type, name, phone_office, phone_dispatcher, phone_emergency, schedule, source FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.PhoneOffice,
		&i.PhoneDispatcher,
		&i.PhoneEmergency,
		&i.Schedule,
		&i.Source,
	)
	return i, err
}

const listEntrances = `-- name: ListEntrances :many
SELECT id, house_id, number FROM entrances WHERE house_id = $1 ORDER BY number
`

func (q *Queries) ListEntrances(ctx context.Context, houseID string) ([]Entrance, error) {
	rows, err := q.db.Query(ctx, listEntrances, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entrance
	for rows.Next() {
		var i Entrance
		if err := rows.Scan(&i.ID, &i.HouseID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseObjects = `-- name: ListHouseObjects :many
SELECT id, house_id, COALESCE(entrance_id, '')::text AS entrance_id, category, label, qr_code
FROM asset_objects
WHERE house_id = $1
ORDER BY id
`

type ListHouseObjectsRow struct {
	ID         string
	HouseID    string
	EntranceID string
	Category   string
	Label      string
	QrCode     string
}

func (q *Queries) ListHouseObjects(ctx context.Context, houseID string) ([]ListHouseObjectsRow, error) {
	rows, err := q.db.Query(ctx, listHouseObjects, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseObjectsRow
	for rows.Next() {
		var i ListHouseObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.EntranceID,
			&i.Category,
			&i.Label,
			&i.QrCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearestHouses = `-- name: NearestHouses :many
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses
ORDER BY (lat - $1::float8) ^ 2 + ((lon - $2::float8) * cos(radians($1::float8))) ^ 2
LIMIT $3
`

type NearestHousesParams struct {
	Lat     float64
	Lon     float64
	MaxRows int32
}

// Плоская аппроксимация расстояния: для радиуса в пару километров точности хватает.
func (q *Queries) NearestHouses(ctx context.Context, arg NearestHousesParams) ([]House, error) {
	rows, err := q.db.Query(ctx, nearestHouses, arg.Lat, arg.Lon, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []House
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.District,
			&i.YearBuilt,
			&i.Floors,
			&i.EntrancesCount,
			&i.OrganizationID,
			&i.Lat,
			&i.Lon,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHouses = `-- name: SearchHouses :many
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses
WHERE address ILIKE '%' || $1::text || '%'
ORDER BY address
LIMIT 20
`

func (q *Queries) SearchHouses(ctx context.Context, query string) ([]House, error) {
	rows, err := q.db.Query(ctx, searchHouses, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []House
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.District,
			&i.YearBuilt,
			&i.Floors,
			&i.EntrancesCount,
			&i.OrganizationID,
			&i.Lat,
			&i.Lon,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
