// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: houses.sql

package sqlcdb

import (
	"context"
)

const ensureEntrances = `-- name: EnsureEntrances :exec
INSERT INTO entrances (id, house_id, number)
SELECT $1::text || '-e' || n, $1::text, n
FROM generate_series(1, $2::int) AS n
ON CONFLICT (id) DO NOTHING
`

type EnsureEntrancesParams struct {
	HouseID        string
	EntrancesCount int32
}

// Подъезды 1..N; лишние старые не удаляются: на них могут ссылаться заявки.
func (q *Queries) EnsureEntrances(ctx context.Context, arg EnsureEntrancesParams) error {
	_, err := q.db.Exec(ctx, ensureEntrances, arg.HouseID, arg.EntrancesCount)
	return err
}

const ensureHouseObjects = `-- name: EnsureHouseObjects :exec
INSERT INTO asset_objects (id, house_id, entrance_id, category, label, qr_code)
SELECT e.id || '-lift', e.house_id, e.id, 'lift', 'подъезд ' || e.number || ', пассажирский лифт', e.id || '-lift'
FROM entrances e WHERE e.house_id = $1
UNION ALL
SELECT e.id || '-light', e.house_id, e.id, 'lighting', 'подъезд ' || e.number || ', лестничная клетка', e.id || '-light'
FROM entrances e WHERE e.house_id = $1
UNION ALL
SELECT $1::text || '-roof', $1::text, NULL, 'leak', 'кровля', $1::text || '-roof'
UNION ALL
SELECT $1::text || '-trash', $1::text, NULL, 'garbage', 'мусоропровод', $1::text || '-trash'
ON CONFLICT (id) DO NOTHING
`

// Те же объекты и коды, что в модельных данных (миграция 00002): лифт и свет в подъезде, кровля, мусоропровод.
func (q *Queries) EnsureHouseObjects(ctx context.Context, houseID string) error {
	_, err := q.db.Exec(ctx, ensureHouseObjects, houseID)
	return err
}

const getHouse = `-- name: GetHouse :one
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses WHERE id = $1
`

func (q *Queries) GetHouse(ctx context.Context, id string) (House, error) {
	row := q.db.QueryRow(ctx, getHouse, id)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.District,
		&i.YearBuilt,
		&i.Floors,
		&i.EntrancesCount,
		&i.OrganizationID,
		&i.Lat,
		&i.Lon,
		&i.Source,
	)
	return i, err
}

const getObjectByCode = `-- name: GetObjectByCode :one
SELECT id, house_id, COALESCE(entrance_id, '')::text AS entrance_id, category, label, qr_code
FROM asset_objects
WHERE qr_code = $1
`

type GetObjectByCodeRow struct {
	ID         string
	HouseID    string
	EntranceID string
	Category   string
	Label      string
	QrCode     string
}

func (q *Queries) GetObjectByCode(ctx context.Context, qrCode string) (GetObjectByCodeRow, error) {
	row := q.db.QueryRow(ctx, getObjectByCode, qrCode)
	var i GetObjectByCodeRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.EntranceID,
		&i.Category,
		&i.Label,
		&i.QrCode,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, type, name, phone_office, phone_dispatcher, phone_emergency, schedule, source FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.PhoneOffice,
		&i.PhoneDispatcher,
		&i.PhoneEmergency,
		&i.Schedule,
		&i.Source,
	)
	return i, err
}

const listDistrictOrganizations = `-- name: ListDistrictOrganizations :many
SELECT DISTINCT o.id, o.type, o.name, o.phone_office, o.phone_dispatcher, o.phone_emergency, o.schedule, o.source FROM organizations o
JOIN houses h ON h.organization_id = o.id
WHERE h.district = $1
ORDER BY o.name
`

func (q *Queries) ListDistrictOrganizations(ctx context.Context, district string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listDistrictOrganizations, district)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.PhoneOffice,
			&i.PhoneDispatcher,
			&i.PhoneEmergency,
			&i.Schedule,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntrances = `-- name: ListEntrances :many
SELECT id, house_id, number FROM entrances WHERE house_id = $1 ORDER BY number
`

func (q *Queries) ListEntrances(ctx context.Context, houseID string) ([]Entrance, error) {
	rows, err := q.db.Query(ctx, listEntrances, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entrance
	for rows.Next() {
		var i Entrance
		if err := rows.Scan(&i.ID, &i.HouseID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseObjects = `-- name: ListHouseObjects :many
SELECT id, house_id, COALESCE(entrance_id, '')::text AS entrance_id, category, label, qr_code
FROM asset_objects
WHERE house_id = $1
ORDER BY id
`

type ListHouseObjectsRow struct {
	ID         string
	HouseID    string
	EntranceID string
	Category   string
	Label      string
	QrCode     string
}

func (q *Queries) ListHouseObjects(ctx context.Context, houseID string) ([]ListHouseObjectsRow, error) {
	rows, err := q.db.Query(ctx, listHouseObjects, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseObjectsRow
	for rows.Next() {
		var i ListHouseObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.EntranceID,
			&i.Category,
			&i.Label,
			&i.QrCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationHouses = `-- name: ListOrganizationHouses :many
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses WHERE organization_id = $1 ORDER BY address
`

func (q *Queries) ListOrganizationHouses(ctx context.Context, organizationID string) ([]House, error) {
	rows, err := q.db.Query(ctx, listOrganizationHouses, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []House
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.District,
			&i.YearBuilt,
			&i.Floors,
			&i.EntrancesCount,
			&i.OrganizationID,
			&i.Lat,
			&i.Lon,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearestHouses = `-- name: NearestHouses :many
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses
WHERE NOT (lat = 0 AND lon = 0)
ORDER BY (lat - $1::float8) ^ 2 + ((lon - $2::float8) * cos(radians($1::float8))) ^ 2
LIMIT $3
`

type NearestHousesParams struct {
	Lat     float64
	Lon     float64
	MaxRows int32
}

// Плоская аппроксимация расстояния: для радиуса в пару километров точности хватает.
// Дома без координат (импорт, где геокодер не нашёл адрес) в выдачу не попадают.
func (q *Queries) NearestHouses(ctx context.Context, arg NearestHousesParams) ([]House, error) {
	rows, err := q.db.Query(ctx, nearestHouses, arg.Lat, arg.Lon, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []House
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.District,
			&i.YearBuilt,
			&i.Floors,
			&i.EntrancesCount,
			&i.OrganizationID,
			&i.Lat,
			&i.Lon,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHouses = `-- name: SearchHouses :many
SELECT id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source FROM houses
WHERE NOT EXISTS (
    SELECT 1
    FROM unnest(string_to_array(trim(regexp_replace($1::text, '[,.\-]+', ' ', 'g')), ' ')) AS w
    WHERE w <> '' AND address NOT ILIKE '%' || w || '%'
)
ORDER BY address
LIMIT 20
`

func (q *Queries) SearchHouses(ctx context.Context, query string) ([]House, error) {
	rows, err := q.db.Query(ctx, searchHouses, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []House
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.District,
			&i.YearBuilt,
			&i.Floors,
			&i.EntrancesCount,
			&i.OrganizationID,
			&i.Lat,
			&i.Lon,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHouse = `-- name: UpsertHouse :one
INSERT INTO houses (id, address, district, year_built, floors, entrances_count, organization_id, lat, lon, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    address = EXCLUDED.address, district = EXCLUDED.district, year_built = EXCLUDED.year_built,
    floors = EXCLUDED.floors, entrances_count = EXCLUDED.entrances_count,
    organization_id = EXCLUDED.organization_id, lat = EXCLUDED.lat, lon = EXCLUDED.lon, source = EXCLUDED.source
RETURNING (xmax = 0)::bool AS created
`

type UpsertHouseParams struct {
	ID             string
	Address        string
	District       string
	YearBuilt      int32
	Floors         int32
	EntrancesCount int32
	OrganizationID string
	Lat            float64
	Lon            float64
	Source         string
}

// Импорт реестра: дом обновляется по id. xmax = 0 только у только что вставленной строки.
func (q *Queries) UpsertHouse(ctx context.Context, arg UpsertHouseParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertHouse,
		arg.ID,
		arg.Address,
		arg.District,
		arg.YearBuilt,
		arg.Floors,
		arg.EntrancesCount,
		arg.OrganizationID,
		arg.Lat,
		arg.Lon,
		arg.Source,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}

const upsertOrganization = `-- name: UpsertOrganization :exec
INSERT INTO organizations (id, type, name, phone_office, phone_dispatcher, phone_emergency, schedule, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    phone_office = EXCLUDED.phone_office,
    phone_dispatcher = EXCLUDED.phone_dispatcher,
    phone_emergency = EXCLUDED.phone_emergency,
    schedule = EXCLUDED.schedule
`

type UpsertOrganizationParams struct {
	ID              string
	Type            string
	Name            string
	PhoneOffice     string
	PhoneDispatcher string
	PhoneEmergency  string
	Schedule        string
	Source          string
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) error {
	_, err := q.db.Exec(ctx, upsertOrganization,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.PhoneOffice,
		arg.PhoneDispatcher,
		arg.PhoneEmergency,
		arg.Schedule,
		arg.Source,
	)
	return err
}
