// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const findSimilarIssues = `-- name: FindSimilarIssues :many
SELECT id, number, house_id, COALESCE(object_id, '')::text AS object_id, category, title, description,
       responsible_org_id, status, status_at, status_comment, created_by, created_at, deadline_at, overdue_at, reopened_at
FROM issues
WHERE house_id = $1
  AND category = $2
  AND ($3::text = '' OR object_id IS NULL OR object_id = $3::text)
  AND status NOT IN ('done', 'rejected')
  AND created_at >= $4
ORDER BY (object_id = $3::text) DESC NULLS LAST, created_at DESC
LIMIT 5
`

type FindSimilarIssuesParams struct {
	HouseID  string
	Category string
	ObjectID string
	Since    time.Time
}

type FindSimilarIssuesRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) FindSimilarIssues(ctx context.Context, arg FindSimilarIssuesParams) ([]FindSimilarIssuesRow, error) {
	rows, err := q.db.Query(ctx, findSimilarIssues,
		arg.HouseID,
		arg.Category,
		arg.ObjectID,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarIssuesRow
	for rows.Next() {
		var i FindSimilarIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssue = `-- name: GetIssue :one
SELECT id, number, house_id, COALESCE(object_id, '')::text AS object_id, category, title, description,
       responsible_org_id, status, status_at, status_comment, created_by, created_at, deadline_at, overdue_at, reopened_at
FROM issues
WHERE id = $1
`

type GetIssueRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) GetIssue(ctx context.Context, id string) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.HouseID,
		&i.ObjectID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.ResponsibleOrgID,
		&i.Status,
		&i.StatusAt,
		&i.StatusComment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeadlineAt,
		&i.OverdueAt,
		&i.ReopenedAt,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO issue_confirmations (issue_id, user_id, done_at, fixed, at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertAnswerParams struct {
	IssueID string
	UserID  int64
	DoneAt  time.Time
	Fixed   bool
	At      time.Time
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAnswer,
		arg.IssueID,
		arg.UserID,
		arg.DoneAt,
		arg.Fixed,
		arg.At,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO issue_events (issue_id, kind, user_id, status, comment, at)
VALUES ($1, $2, NULLIF($3::bigint, 0), $4, $5, $6)
`

type InsertEventParams struct {
	IssueID string
	Kind    string
	UserID  int64
	Status  string
	Comment string
	At      time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.IssueID,
		arg.Kind,
		arg.UserID,
		arg.Status,
		arg.Comment,
		arg.At,
	)
	return err
}

const insertIssue = `-- name: InsertIssue :one
INSERT INTO issues (id, house_id, object_id, category, title, description, responsible_org_id,
                    status, status_at, status_comment, created_by, created_at, deadline_at)
VALUES ($1, $2, NULLIF($3::text, ''), $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
RETURNING number
`

type InsertIssueParams struct {
	ID               string
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
}

func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIssue,
		arg.ID,
		arg.HouseID,
		arg.ObjectID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.ResponsibleOrgID,
		arg.Status,
		arg.StatusAt,
		arg.StatusComment,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.DeadlineAt,
	)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO issue_participants (issue_id, user_id, joined_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertParticipantParams struct {
	IssueID  string
	UserID   int64
	JoinedAt time.Time
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.Exec(ctx, insertParticipant, arg.IssueID, arg.UserID, arg.JoinedAt)
	return err
}

const listCurrentAnswers = `-- name: ListCurrentAnswers :many
SELECT c.issue_id, c.user_id, c.fixed, c.done_at, c.at, COALESCE(c.stars, 0)::int AS stars
FROM issue_confirmations c
JOIN issues i ON i.id = c.issue_id
WHERE c.issue_id = ANY ($1::uuid[])
  AND i.status = 'done'
  AND c.done_at = i.status_at
ORDER BY c.at, c.user_id
`

type ListCurrentAnswersRow struct {
	IssueID string
	UserID  int64
	Fixed   bool
	DoneAt  time.Time
	At      time.Time
	Stars   int32
}

// Ответы на текущее «выполнено»: у заявки в другом статусе их нет.
func (q *Queries) ListCurrentAnswers(ctx context.Context, issueIds []string) ([]ListCurrentAnswersRow, error) {
	rows, err := q.db.Query(ctx, listCurrentAnswers, issueIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentAnswersRow
	for rows.Next() {
		var i ListCurrentAnswersRow
		if err := rows.Scan(
			&i.IssueID,
			&i.UserID,
			&i.Fixed,
			&i.DoneAt,
			&i.At,
			&i.Stars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictOverdue = `-- name: ListDistrictOverdue :many
SELECT i.id, i.number, i.house_id, COALESCE(i.object_id, '')::text AS object_id, i.category, i.title, i.description,
       i.responsible_org_id, i.status, i.status_at, i.status_comment, i.created_by, i.created_at, i.deadline_at, i.overdue_at, i.reopened_at
FROM issues i
JOIN houses h ON h.id = i.house_id
WHERE h.district = $1
  AND i.status NOT IN ('done', 'rejected')
  AND i.deadline_at < $2
ORDER BY i.deadline_at
LIMIT $3
`

type ListDistrictOverdueParams struct {
	District string
	Now      time.Time
	MaxRows  int32
}

type ListDistrictOverdueRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) ListDistrictOverdue(ctx context.Context, arg ListDistrictOverdueParams) ([]ListDistrictOverdueRow, error) {
	rows, err := q.db.Query(ctx, listDistrictOverdue, arg.District, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistrictOverdueRow
	for rows.Next() {
		var i ListDistrictOverdueRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseIssues = `-- name: ListHouseIssues :many
SELECT id, number, house_id, COALESCE(object_id, '')::text AS object_id, category, title, description,
       responsible_org_id, status, status_at, status_comment, created_by, created_at, deadline_at, overdue_at, reopened_at
FROM issues
WHERE house_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListHouseIssuesParams struct {
	HouseID string
	MaxRows int32
}

type ListHouseIssuesRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) ListHouseIssues(ctx context.Context, arg ListHouseIssuesParams) ([]ListHouseIssuesRow, error) {
	rows, err := q.db.Query(ctx, listHouseIssues, arg.HouseID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseIssuesRow
	for rows.Next() {
		var i ListHouseIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueEvents = `-- name: ListIssueEvents :many
SELECT kind, COALESCE(user_id, 0)::bigint AS user_id, status, comment, at
FROM issue_events
WHERE issue_id = $1
ORDER BY at, id
`

type ListIssueEventsRow struct {
	Kind    string
	UserID  int64
	Status  string
	Comment string
	At      time.Time
}

func (q *Queries) ListIssueEvents(ctx context.Context, issueID string) ([]ListIssueEventsRow, error) {
	rows, err := q.db.Query(ctx, listIssueEvents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueEventsRow
	for rows.Next() {
		var i ListIssueEventsRow
		if err := rows.Scan(
			&i.Kind,
			&i.UserID,
			&i.Status,
			&i.Comment,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgQueue = `-- name: ListOrgQueue :many
SELECT id, number, house_id, COALESCE(object_id, '')::text AS object_id, category, title, description,
       responsible_org_id, status, status_at, status_comment, created_by, created_at, deadline_at, overdue_at, reopened_at
FROM issues
WHERE responsible_org_id = $1
ORDER BY status IN ('done', 'rejected'), deadline_at
LIMIT $2
`

type ListOrgQueueParams struct {
	OrgID   string
	MaxRows int32
}

type ListOrgQueueRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) ListOrgQueue(ctx context.Context, arg ListOrgQueueParams) ([]ListOrgQueueRow, error) {
	rows, err := q.db.Query(ctx, listOrgQueue, arg.OrgID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgQueueRow
	for rows.Next() {
		var i ListOrgQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueUnmarked = `-- name: ListOverdueUnmarked :many
SELECT id, number, house_id, COALESCE(object_id, '')::text AS object_id, category, title, description,
       responsible_org_id, status, status_at, status_comment, created_by, created_at, deadline_at, overdue_at, reopened_at
FROM issues
WHERE overdue_at IS NULL
  AND status NOT IN ('done', 'rejected')
  AND deadline_at < $1
ORDER BY deadline_at
LIMIT $2
`

type ListOverdueUnmarkedParams struct {
	Now     time.Time
	MaxRows int32
}

type ListOverdueUnmarkedRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) ListOverdueUnmarked(ctx context.Context, arg ListOverdueUnmarkedParams) ([]ListOverdueUnmarkedRow, error) {
	rows, err := q.db.Query(ctx, listOverdueUnmarked, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueUnmarkedRow
	for rows.Next() {
		var i ListOverdueUnmarkedRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantIssues = `-- name: ListParticipantIssues :many
SELECT i.id, i.number, i.house_id, COALESCE(i.object_id, '')::text AS object_id, i.category, i.title, i.description,
       i.responsible_org_id, i.status, i.status_at, i.status_comment, i.created_by, i.created_at, i.deadline_at, i.overdue_at, i.reopened_at
FROM issues i
JOIN issue_participants p ON p.issue_id = i.id
WHERE p.user_id = $1
ORDER BY i.status IN ('done', 'rejected'), i.created_at DESC
LIMIT $2
`

type ListParticipantIssuesParams struct {
	UserID  int64
	MaxRows int32
}

type ListParticipantIssuesRow struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         string
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	ReopenedAt       *time.Time
}

func (q *Queries) ListParticipantIssues(ctx context.Context, arg ListParticipantIssuesParams) ([]ListParticipantIssuesRow, error) {
	rows, err := q.db.Query(ctx, listParticipantIssues, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantIssuesRow
	for rows.Next() {
		var i ListParticipantIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.HouseID,
			&i.ObjectID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.ResponsibleOrgID,
			&i.Status,
			&i.StatusAt,
			&i.StatusComment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeadlineAt,
			&i.OverdueAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT issue_id, user_id, joined_at
FROM issue_participants
WHERE issue_id = ANY ($1::uuid[])
ORDER BY joined_at, user_id
`

func (q *Queries) ListParticipants(ctx context.Context, issueIds []string) ([]IssueParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipants, issueIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueParticipant
	for rows.Next() {
		var i IssueParticipant
		if err := rows.Scan(&i.IssueID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIssue = `-- name: LockIssue :exec
SELECT 1 FROM issues WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockIssue(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockIssue, id)
	return err
}

const rateAnswer = `-- name: RateAnswer :exec
UPDATE issue_confirmations
SET stars = $1
WHERE issue_id = $2 AND user_id = $3 AND done_at = $4 AND stars IS NULL
`

type RateAnswerParams struct {
	Stars   pgtype.Int2
	IssueID string
	UserID  int64
	DoneAt  time.Time
}

// Оценка ставится один раз: повтор в гонке двух нажатий не перезапишет первую.
func (q *Queries) RateAnswer(ctx context.Context, arg RateAnswerParams) error {
	_, err := q.db.Exec(ctx, rateAnswer,
		arg.Stars,
		arg.IssueID,
		arg.UserID,
		arg.DoneAt,
	)
	return err
}

const updateIssueState = `-- name: UpdateIssueState :exec
UPDATE issues
SET status = $1, status_at = $2, status_comment = $3, overdue_at = $4,
    deadline_at = $5, reopened_at = $6
WHERE id = $7
`

type UpdateIssueStateParams struct {
	Status        string
	StatusAt      time.Time
	StatusComment string
	OverdueAt     *time.Time
	DeadlineAt    time.Time
	ReopenedAt    *time.Time
	ID            string
}

// Срок меняется, когда жители возвращают заявку в работу: он считается заново по справочнику.
func (q *Queries) UpdateIssueState(ctx context.Context, arg UpdateIssueStateParams) error {
	_, err := q.db.Exec(ctx, updateIssueState,
		arg.Status,
		arg.StatusAt,
		arg.StatusComment,
		arg.OverdueAt,
		arg.DeadlineAt,
		arg.ReopenedAt,
		arg.ID,
	)
	return err
}
