// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlcdb

import (
	"context"
	"time"
)

const listFirstResponses = `-- name: ListFirstResponses :many
SELECT i.created_at, min(e.at)::timestamptz AS responded_at
FROM issues i
JOIN issue_events e ON e.issue_id = i.id AND e.kind = 'status_changed'
WHERE i.responsible_org_id = $1 AND i.created_at >= $2
GROUP BY i.id, i.created_at
`

type ListFirstResponsesParams struct {
	OrgID string
	Since time.Time
}

type ListFirstResponsesRow struct {
	CreatedAt   time.Time
	RespondedAt time.Time
}

func (q *Queries) ListFirstResponses(ctx context.Context, arg ListFirstResponsesParams) ([]ListFirstResponsesRow, error) {
	rows, err := q.db.Query(ctx, listFirstResponses, arg.OrgID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFirstResponsesRow
	for rows.Next() {
		var i ListFirstResponsesRow
		if err := rows.Scan(&i.CreatedAt, &i.RespondedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSampleShift = `-- name: LockSampleShift :exec
SELECT pg_advisory_xact_lock(7340301)
`

// Сдвиг примера данных идёт под блокировкой до конца транзакции: два экземпляра api не сдвинут дважды.
func (q *Queries) LockSampleShift(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSampleShift)
	return err
}

const orgMetricCounts = `-- name: OrgMetricCounts :one
SELECT count(*) FILTER (WHERE i.created_at >= $1)::int AS issues,
       COALESCE(sum(p.n) FILTER (WHERE i.created_at >= $1), 0)::int AS reports,
       count(*) FILTER (WHERE i.status IN ('done', 'rejected') AND i.status_at >= $1)::int AS closed_total,
       count(*) FILTER (WHERE i.status IN ('done', 'rejected') AND i.status_at >= $1
                          AND i.status_at <= i.deadline_at)::int AS closed_on_time,
       count(*) FILTER (WHERE i.status = 'done' AND i.status_at >= $1 AND EXISTS (
                            SELECT 1 FROM issue_confirmations c
                            WHERE c.issue_id = i.id AND c.done_at = i.status_at AND c.fixed))::int AS confirmed,
       count(*) FILTER (WHERE i.reopened_at >= $1)::int AS reopened,
       count(*) FILTER (WHERE i.status NOT IN ('done', 'rejected'))::int AS open_total,
       count(*) FILTER (WHERE i.status NOT IN ('done', 'rejected') AND i.deadline_at < $2)::int AS overdue_open,
       COALESCE(sum(r.s), 0)::int AS rating_sum,
       COALESCE(sum(r.n), 0)::int AS ratings,
       COALESCE(bool_or(i.sample), false)::boolean AS sample_data
FROM issues i
LEFT JOIN LATERAL (SELECT count(*) AS n FROM issue_participants ip WHERE ip.issue_id = i.id) p ON true
LEFT JOIN LATERAL (SELECT sum(c.stars) AS s, count(c.stars) AS n
                   FROM issue_confirmations c
                   WHERE c.issue_id = i.id AND c.done_at >= $1) r ON true
WHERE i.responsible_org_id = $3
`

type OrgMetricCountsParams struct {
	Since time.Time
	Now   time.Time
	OrgID string
}

type OrgMetricCountsRow struct {
	Issues       int32
	Reports      int32
	ClosedTotal  int32
	ClosedOnTime int32
	Confirmed    int32
	Reopened     int32
	OpenTotal    int32
	OverdueOpen  int32
	RatingSum    int32
	Ratings      int32
	SampleData   bool
}

// Оценки ремонтов, отмеченных выполненными за период (ADR-022).
func (q *Queries) OrgMetricCounts(ctx context.Context, arg OrgMetricCountsParams) (OrgMetricCountsRow, error) {
	row := q.db.QueryRow(ctx, orgMetricCounts, arg.Since, arg.Now, arg.OrgID)
	var i OrgMetricCountsRow
	err := row.Scan(
		&i.Issues,
		&i.Reports,
		&i.ClosedTotal,
		&i.ClosedOnTime,
		&i.Confirmed,
		&i.Reopened,
		&i.OpenTotal,
		&i.OverdueOpen,
		&i.RatingSum,
		&i.Ratings,
		&i.SampleData,
	)
	return i, err
}

const sampleLatestAt = `-- name: SampleLatestAt :one
SELECT COALESCE(max(t), $1::timestamptz)::timestamptz AS latest
FROM (
    SELECT greatest(i.created_at, i.status_at, i.overdue_at, i.reopened_at) AS t FROM issues i WHERE i.sample
    UNION ALL
    SELECT c.at FROM issue_confirmations c JOIN issues i ON i.id = c.issue_id WHERE i.sample
    UNION ALL
    SELECT e.at FROM issue_events e JOIN issues i ON i.id = e.issue_id WHERE i.sample
    UNION ALL
    SELECT p.joined_at FROM issue_participants p JOIN issues i ON i.id = p.issue_id WHERE i.sample
) AS x
`

// Самое позднее событие примера данных (срок не в счёт: он может быть в будущем).
func (q *Queries) SampleLatestAt(ctx context.Context, now time.Time) (time.Time, error) {
	row := q.db.QueryRow(ctx, sampleLatestAt, now)
	var latest time.Time
	err := row.Scan(&latest)
	return latest, err
}

const shiftSampleConfirmations = `-- name: ShiftSampleConfirmations :exec
UPDATE issue_confirmations c
SET done_at = c.done_at + make_interval(days => $1::int),
    at      = c.at + make_interval(days => $1::int)
FROM issues i
WHERE i.id = c.issue_id AND i.sample
`

// done_at сдвигается вместе со status_at, иначе ответы перестанут относиться к текущему «выполнено».
func (q *Queries) ShiftSampleConfirmations(ctx context.Context, days int32) error {
	_, err := q.db.Exec(ctx, shiftSampleConfirmations, days)
	return err
}

const shiftSampleEvents = `-- name: ShiftSampleEvents :exec
UPDATE issue_events e
SET at = e.at + make_interval(days => $1::int)
FROM issues i
WHERE i.id = e.issue_id AND i.sample
`

func (q *Queries) ShiftSampleEvents(ctx context.Context, days int32) error {
	_, err := q.db.Exec(ctx, shiftSampleEvents, days)
	return err
}

const shiftSampleIssues = `-- name: ShiftSampleIssues :exec
UPDATE issues
SET created_at  = created_at + make_interval(days => $1::int),
    status_at   = status_at + make_interval(days => $1::int),
    deadline_at = deadline_at + make_interval(days => $1::int),
    overdue_at  = overdue_at + make_interval(days => $1::int),
    reopened_at = reopened_at + make_interval(days => $1::int)
WHERE sample
`

func (q *Queries) ShiftSampleIssues(ctx context.Context, days int32) error {
	_, err := q.db.Exec(ctx, shiftSampleIssues, days)
	return err
}

const shiftSampleParticipants = `-- name: ShiftSampleParticipants :exec
UPDATE issue_participants p
SET joined_at = p.joined_at + make_interval(days => $1::int)
FROM issues i
WHERE i.id = p.issue_id AND i.sample
`

func (q *Queries) ShiftSampleParticipants(ctx context.Context, days int32) error {
	_, err := q.db.Exec(ctx, shiftSampleParticipants, days)
	return err
}
