// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetObject struct {
	ID         string
	HouseID    string
	EntranceID pgtype.Text
	Category   string
	Label      string
	QrCode     string
}

type BotCard struct {
	IssueID   string
	UserID    int64
	Mid       string
	UpdatedAt time.Time
}

type BotPending struct {
	UserID    int64
	Action    string
	Ref       string
	Text      string
	ExpiresAt time.Time
}

type Entrance struct {
	ID      string
	HouseID string
	Number  int32
}

type House struct {
	ID             string
	Address        string
	District       string
	YearBuilt      int32
	Floors         int32
	EntrancesCount int32
	OrganizationID string
	Lat            float64
	Lon            float64
	Source         string
}

type Issue struct {
	ID               string
	Number           int64
	HouseID          string
	ObjectID         pgtype.Text
	Category         string
	Title            string
	Description      string
	ResponsibleOrgID string
	Status           string
	StatusAt         time.Time
	StatusComment    string
	CreatedBy        int64
	CreatedAt        time.Time
	DeadlineAt       time.Time
	OverdueAt        *time.Time
	Sample           bool
	ReopenedAt       *time.Time
}

type IssueConfirmation struct {
	IssueID string
	UserID  int64
	DoneAt  time.Time
	Fixed   bool
	At      time.Time
	Stars   pgtype.Int2
}

type IssueEvent struct {
	ID      int64
	IssueID string
	Kind    string
	UserID  pgtype.Int8
	Status  string
	Comment string
	At      time.Time
}

type IssueParticipant struct {
	IssueID  string
	UserID   int64
	JoinedAt time.Time
}

type IssuePhoto struct {
	ID         string
	IssueID    string
	UploadedBy int64
	Width      int32
	Height     int32
	SizeBytes  int32
	CreatedAt  time.Time
}

type Organization struct {
	ID              string
	Type            string
	Name            string
	PhoneOffice     string
	PhoneDispatcher string
	PhoneEmergency  string
	Schedule        string
	Source          string
}

type Outbox struct {
	ID            int64
	Kind          string
	IssueID       *string
	UserID        int64
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastError     string
	CreatedAt     time.Time
	ProposalID    *string
}

type Poll struct {
	ID         string
	HouseID    string
	ProposalID *string
	Question   string
	Options    []string
	CreatedAt  time.Time
	ClosesAt   time.Time
}

type PollVote struct {
	PollID  string
	UserID  int64
	Option  int32
	VotedAt time.Time
}

type ProcessedUpdate struct {
	Key        string
	ReceivedAt time.Time
}

type Proposal struct {
	ID         string
	HouseID    string
	AuthorID   int64
	Text       string
	Status     string
	Answer     string
	CreatedAt  time.Time
	AnsweredAt *time.Time
}

type User struct {
	ID              int64
	MaxUserID       pgtype.Int8
	DemoKey         pgtype.Text
	FirstName       string
	Phone           string
	HouseID         pgtype.Text
	Role            string
	OrganizationID  pgtype.Text
	ConsentVersion  string
	ConsentAt       *time.Time
	DeletedAt       *time.Time
	CreatedAt       time.Time
	District        string
	ChairmanHouseID pgtype.Text
	RoleSwitched    bool
}
