// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: office.sql

package sqlcdb

import (
	"context"
	"time"
)

const cancelAppointment = `-- name: CancelAppointment :exec
UPDATE appointments SET status = 'cancelled' WHERE id = $1
`

func (q *Queries) CancelAppointment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelAppointment, id)
	return err
}

const deleteMaintenanceAlert = `-- name: DeleteMaintenanceAlert :exec
DELETE FROM maintenance_alerts WHERE id = $1
`

func (q *Queries) DeleteMaintenanceAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceAlert, id)
	return err
}

const getAppointment = `-- name: GetAppointment :one
SELECT a.id::text AS id, a.house_id, h.address, a.user_id, u.first_name AS user_name, a.specialist, a.topic, a.slot_at, a.status, a.created_at
FROM appointments a
JOIN houses h ON h.id = a.house_id
JOIN users u ON u.id = a.user_id
WHERE a.id = $1
`

type GetAppointmentRow struct {
	ID         string
	HouseID    string
	Address    string
	UserID     int64
	UserName   string
	Specialist string
	Topic      string
	SlotAt     time.Time
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) GetAppointment(ctx context.Context, id string) (GetAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i GetAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.Address,
		&i.UserID,
		&i.UserName,
		&i.Specialist,
		&i.Topic,
		&i.SlotAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAppointment = `-- name: InsertAppointment :exec
INSERT INTO appointments (id, house_id, user_id, specialist, topic, slot_at, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAppointmentParams struct {
	ID         string
	HouseID    string
	UserID     int64
	Specialist string
	Topic      string
	SlotAt     time.Time
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error {
	_, err := q.db.Exec(ctx, insertAppointment,
		arg.ID,
		arg.HouseID,
		arg.UserID,
		arg.Specialist,
		arg.Topic,
		arg.SlotAt,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertMaintenanceAlert = `-- name: InsertMaintenanceAlert :exec
INSERT INTO maintenance_alerts (id, house_id, category, title, description, starts_at, ends_at, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMaintenanceAlertParams struct {
	ID          string
	HouseID     string
	Category    string
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	CreatedBy   int64
	CreatedAt   time.Time
}

func (q *Queries) InsertMaintenanceAlert(ctx context.Context, arg InsertMaintenanceAlertParams) error {
	_, err := q.db.Exec(ctx, insertMaintenanceAlert,
		arg.ID,
		arg.HouseID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listActiveMaintenanceByHouse = `-- name: ListActiveMaintenanceByHouse :many
SELECT id::text AS id, house_id, category, title, description, starts_at, ends_at, created_by, created_at
FROM maintenance_alerts
WHERE house_id = $1
  AND ends_at > $2
ORDER BY starts_at, id
`

type ListActiveMaintenanceByHouseParams struct {
	HouseID string
	Now     time.Time
}

type ListActiveMaintenanceByHouseRow struct {
	ID          string
	HouseID     string
	Category    string
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	CreatedBy   int64
	CreatedAt   time.Time
}

func (q *Queries) ListActiveMaintenanceByHouse(ctx context.Context, arg ListActiveMaintenanceByHouseParams) ([]ListActiveMaintenanceByHouseRow, error) {
	rows, err := q.db.Query(ctx, listActiveMaintenanceByHouse, arg.HouseID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMaintenanceByHouseRow
	for rows.Next() {
		var i ListActiveMaintenanceByHouseRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceByOrg = `-- name: ListMaintenanceByOrg :many
SELECT m.id::text AS id, m.house_id, h.address, m.category, m.title, m.description, m.starts_at, m.ends_at, m.created_by, m.created_at
FROM maintenance_alerts m
JOIN houses h ON h.id = m.house_id
WHERE h.organization_id = $1
ORDER BY m.ends_at DESC, m.starts_at DESC
LIMIT $2
`

type ListMaintenanceByOrgParams struct {
	OrgID   string
	MaxRows int32
}

type ListMaintenanceByOrgRow struct {
	ID          string
	HouseID     string
	Address     string
	Category    string
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	CreatedBy   int64
	CreatedAt   time.Time
}

func (q *Queries) ListMaintenanceByOrg(ctx context.Context, arg ListMaintenanceByOrgParams) ([]ListMaintenanceByOrgRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByOrg, arg.OrgID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceByOrgRow
	for rows.Next() {
		var i ListMaintenanceByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Address,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgAppointments = `-- name: ListOrgAppointments :many
SELECT a.id::text AS id, a.house_id, h.address, a.user_id, u.first_name AS user_name, a.specialist, a.topic, a.slot_at, a.status, a.created_at
FROM appointments a
JOIN houses h ON h.id = a.house_id
JOIN users u ON u.id = a.user_id
WHERE h.organization_id = $1
ORDER BY (a.status = 'cancelled'), a.slot_at
LIMIT $2
`

type ListOrgAppointmentsParams struct {
	OrgID   string
	MaxRows int32
}

type ListOrgAppointmentsRow struct {
	ID         string
	HouseID    string
	Address    string
	UserID     int64
	UserName   string
	Specialist string
	Topic      string
	SlotAt     time.Time
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) ListOrgAppointments(ctx context.Context, arg ListOrgAppointmentsParams) ([]ListOrgAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listOrgAppointments, arg.OrgID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgAppointmentsRow
	for rows.Next() {
		var i ListOrgAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Address,
			&i.UserID,
			&i.UserName,
			&i.Specialist,
			&i.Topic,
			&i.SlotAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAppointments = `-- name: ListUserAppointments :many
SELECT a.id::text AS id, a.house_id, h.address, a.user_id, u.first_name AS user_name, a.specialist, a.topic, a.slot_at, a.status, a.created_at
FROM appointments a
JOIN houses h ON h.id = a.house_id
JOIN users u ON u.id = a.user_id
WHERE a.user_id = $1
ORDER BY (a.status = 'cancelled'), a.slot_at
LIMIT $2
`

type ListUserAppointmentsParams struct {
	UserID  int64
	MaxRows int32
}

type ListUserAppointmentsRow struct {
	ID         string
	HouseID    string
	Address    string
	UserID     int64
	UserName   string
	Specialist string
	Topic      string
	SlotAt     time.Time
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) ListUserAppointments(ctx context.Context, arg ListUserAppointmentsParams) ([]ListUserAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listUserAppointments, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAppointmentsRow
	for rows.Next() {
		var i ListUserAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Address,
			&i.UserID,
			&i.UserName,
			&i.Specialist,
			&i.Topic,
			&i.SlotAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
