// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcdb

import (
	"context"
	"time"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE outbox
SET status = 'sending', attempts = attempts + 1
WHERE id IN (
    SELECT o.id FROM outbox o
    WHERE o.status = 'pending' AND o.next_attempt_at <= now()
    ORDER BY o.id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, issue_id, proposal_id, user_id, attempts
`

type ClaimNotificationsRow struct {
	ID         int64
	Kind       string
	IssueID    *string
	ProposalID *string
	UserID     int64
	Attempts   int32
}

// Взятые строки переходят в sending и коммитятся сразу: новое изменение заявки
// за время отправки попадёт в очередь отдельной строкой и не потеряется.
func (q *Queries) ClaimNotifications(ctx context.Context, maxRows int32) ([]ClaimNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimNotifications, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationsRow
	for rows.Next() {
		var i ClaimNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IssueID,
			&i.ProposalID,
			&i.UserID,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO outbox (kind, issue_id, proposal_id, user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, issue_id, user_id) WHERE status = 'pending' DO NOTHING
`

type EnqueueNotificationParams struct {
	Kind       string
	IssueID    *string
	ProposalID *string
	UserID     int64
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.Kind,
		arg.IssueID,
		arg.ProposalID,
		arg.UserID,
	)
	return err
}

const getCardMID = `-- name: GetCardMID :one
SELECT mid FROM bot_cards WHERE issue_id = $1 AND user_id = $2
`

type GetCardMIDParams struct {
	IssueID string
	UserID  int64
}

func (q *Queries) GetCardMID(ctx context.Context, arg GetCardMIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getCardMID, arg.IssueID, arg.UserID)
	var mid string
	err := row.Scan(&mid)
	return mid, err
}

const markNotificationDone = `-- name: MarkNotificationDone :exec
UPDATE outbox SET status = 'done', last_error = '' WHERE id = $1
`

func (q *Queries) MarkNotificationDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationDone, id)
	return err
}

const releaseSending = `-- name: ReleaseSending :exec
UPDATE outbox o
SET status = CASE
        WHEN EXISTS (
            SELECT 1 FROM outbox p
            WHERE p.status = 'pending' AND p.kind = o.kind AND p.issue_id = o.issue_id AND p.user_id = o.user_id
        ) THEN 'done'
        ELSE 'pending'
    END
WHERE o.status = 'sending'
`

// После перезапуска: недоотправленное возвращается в очередь, если его не заменила новая строка.
func (q *Queries) ReleaseSending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseSending)
	return err
}

const retryNotification = `-- name: RetryNotification :exec
UPDATE outbox o
SET status = CASE
        WHEN $1::bool THEN 'failed'
        WHEN EXISTS (
            SELECT 1 FROM outbox p
            WHERE p.status = 'pending' AND p.kind = o.kind AND p.issue_id = o.issue_id AND p.user_id = o.user_id
        ) THEN 'done'
        ELSE 'pending'
    END,
    next_attempt_at = $2,
    last_error = $3
WHERE o.id = $4
`

type RetryNotificationParams struct {
	Failed        bool
	NextAttemptAt time.Time
	LastError     string
	ID            int64
}

// Если за время отправки появилась новая строка для того же адресата, эта уже не нужна.
func (q *Queries) RetryNotification(ctx context.Context, arg RetryNotificationParams) error {
	_, err := q.db.Exec(ctx, retryNotification,
		arg.Failed,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const saveCardMID = `-- name: SaveCardMID :exec
INSERT INTO bot_cards (issue_id, user_id, mid)
VALUES ($1, $2, $3)
ON CONFLICT (issue_id, user_id) DO UPDATE SET mid = EXCLUDED.mid, updated_at = now()
`

type SaveCardMIDParams struct {
	IssueID string
	UserID  int64
	Mid     string
}

func (q *Queries) SaveCardMID(ctx context.Context, arg SaveCardMIDParams) error {
	_, err := q.db.Exec(ctx, saveCardMID, arg.IssueID, arg.UserID, arg.Mid)
	return err
}
