// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlcdb

import (
	"context"
	"time"
)

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM issue_photos WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, issue_id, uploaded_by, width, height, size_bytes, created_at
FROM issue_photos
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id string) (IssuePhoto, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i IssuePhoto
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UploadedBy,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const insertPhoto = `-- name: InsertPhoto :exec
INSERT INTO issue_photos (id, issue_id, uploaded_by, width, height, size_bytes, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPhotoParams struct {
	ID         string
	IssueID    string
	UploadedBy int64
	Width      int32
	Height     int32
	SizeBytes  int32
	CreatedAt  time.Time
}

func (q *Queries) InsertPhoto(ctx context.Context, arg InsertPhotoParams) error {
	_, err := q.db.Exec(ctx, insertPhoto,
		arg.ID,
		arg.IssueID,
		arg.UploadedBy,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.CreatedAt,
	)
	return err
}

const listIssuePhotos = `-- name: ListIssuePhotos :many
SELECT id, issue_id, uploaded_by, width, height, size_bytes, created_at
FROM issue_photos
WHERE issue_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListIssuePhotos(ctx context.Context, issueID string) ([]IssuePhoto, error) {
	rows, err := q.db.Query(ctx, listIssuePhotos, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuePhoto
	for rows.Next() {
		var i IssuePhoto
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UploadedBy,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploaderPhotos = `-- name: ListUploaderPhotos :many
SELECT id, issue_id, uploaded_by, width, height, size_bytes, created_at
FROM issue_photos
WHERE uploaded_by = $1
ORDER BY created_at, id
`

func (q *Queries) ListUploaderPhotos(ctx context.Context, uploadedBy int64) ([]IssuePhoto, error) {
	rows, err := q.db.Query(ctx, listUploaderPhotos, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuePhoto
	for rows.Next() {
		var i IssuePhoto
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UploadedBy,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
