// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, max_user_id, demo_key, first_name, phone, house_id, role, organization_id, consent_version, consent_at, deleted_at, created_at, district, chairman_house_id FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MaxUserID,
		&i.DemoKey,
		&i.FirstName,
		&i.Phone,
		&i.HouseID,
		&i.Role,
		&i.OrganizationID,
		&i.ConsentVersion,
		&i.ConsentAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.District,
		&i.ChairmanHouseID,
	)
	return i, err
}

const getUserByDemoKey = `-- name: GetUserByDemoKey :one
SELECT id, max_user_id, demo_key, first_name, phone, house_id, role, organization_id, consent_version, consent_at, deleted_at, created_at, district, chairman_house_id FROM users WHERE demo_key = $1
`

func (q *Queries) GetUserByDemoKey(ctx context.Context, demoKey pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDemoKey, demoKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MaxUserID,
		&i.DemoKey,
		&i.FirstName,
		&i.Phone,
		&i.HouseID,
		&i.Role,
		&i.OrganizationID,
		&i.ConsentVersion,
		&i.ConsentAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.District,
		&i.ChairmanHouseID,
	)
	return i, err
}

const getUserByMaxID = `-- name: GetUserByMaxID :one
SELECT id, max_user_id, demo_key, first_name, phone, house_id, role, organization_id, consent_version, consent_at, deleted_at, created_at, district, chairman_house_id FROM users WHERE max_user_id = $1
`

func (q *Queries) GetUserByMaxID(ctx context.Context, maxUserID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMaxID, maxUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MaxUserID,
		&i.DemoKey,
		&i.FirstName,
		&i.Phone,
		&i.HouseID,
		&i.Role,
		&i.OrganizationID,
		&i.ConsentVersion,
		&i.ConsentAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.District,
		&i.ChairmanHouseID,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (max_user_id, first_name, role)
VALUES ($1, $2, $3)
RETURNING id, max_user_id, demo_key, first_name, phone, house_id, role, organization_id, consent_version, consent_at, deleted_at, created_at, district, chairman_house_id
`

type InsertUserParams struct {
	MaxUserID pgtype.Int8
	FirstName string
	Role      string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.MaxUserID, arg.FirstName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MaxUserID,
		&i.DemoKey,
		&i.FirstName,
		&i.Phone,
		&i.HouseID,
		&i.Role,
		&i.OrganizationID,
		&i.ConsentVersion,
		&i.ConsentAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.District,
		&i.ChairmanHouseID,
	)
	return i, err
}

const markUpdateProcessed = `-- name: MarkUpdateProcessed :execrows
INSERT INTO processed_updates (key) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkUpdateProcessed(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, markUpdateProcessed, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET max_user_id     = $1,
    first_name      = $2,
    phone           = $3,
    house_id        = NULLIF($4::text, ''),
    chairman_house_id = NULLIF($5::text, ''),
    consent_version = $6,
    consent_at      = $7,
    deleted_at      = $8
WHERE id = $9
`

type UpdateUserParams struct {
	MaxUserID       pgtype.Int8
	FirstName       string
	Phone           string
	HouseID         string
	ChairmanHouseID string
	ConsentVersion  string
	ConsentAt       *time.Time
	DeletedAt       *time.Time
	ID              int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.MaxUserID,
		arg.FirstName,
		arg.Phone,
		arg.HouseID,
		arg.ChairmanHouseID,
		arg.ConsentVersion,
		arg.ConsentAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
