#!/bin/bash
set -euo pipefail

# scripts/export-submission.sh — скрипт чистого экспорта репозитория для сдачи жюри (по ADR-007).
# Исключает внутреннюю базу знаний hack-docs/, файлы инструкций CLAUDE.md, настройки .claude/
# и проверяет отсутствие ИИ-меток и секретов.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${1:-$ROOT_DIR/../max-hyuax-submission}"

echo "=== Экспорт решения для сдачи жюри (ADR-007) ==="
echo "Исходный репозиторий: $ROOT_DIR"
echo "Целевой каталог:       $TARGET_DIR"

rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR"

# 1. Копирование разрешённых компонентов проекта
echo "-> Копирование исходных файлов..."
for item in backend miniapp deploy api docs README.md DATA-API.yaml compose.yaml .env.example .dockerignore Taskfile.yml .gitignore; do
    if [ -e "$ROOT_DIR/$item" ]; then
        cp -R "$ROOT_DIR/$item" "$TARGET_DIR/"
    fi
done

# Очистка временных файлов и кэшей сборки
find "$TARGET_DIR" -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true
find "$TARGET_DIR" -type d -name "dist" -exec rm -rf {} + 2>/dev/null || true
find "$TARGET_DIR" -type d -name "bin" -exec rm -rf {} + 2>/dev/null || true
find "$TARGET_DIR" -type f -name "*.out" -delete 2>/dev/null || true
find "$TARGET_DIR" -type f -name "*.exe" -delete 2>/dev/null || true
find "$TARGET_DIR" -type f -name ".DS_Store" -delete 2>/dev/null || true

# 2. Проверка: отсутствие внутренних и запрещённых файлов
echo "-> Проверка исключения закрытых материалов..."
FORBIDDEN_FILES=("hack-docs" "CLAUDE.md" "AGENTS.md" "LEAN-CTX.md" ".claude" ".obsidian" ".idea" ".vscode" ".env")
for f in "${FORBIDDEN_FILES[@]}"; do
    if [ -e "$TARGET_DIR/$f" ]; then
        echo "ОШИБКА: Запрещённый файл $f попал в экспорт!" >&2
        exit 1
    fi
done

# 3. Проверка на отсутствие ИИ-маркеров (п. 9.5 правил хакатона)
echo "-> Проверка на отсутствие меток ИИ..."
AI_MATCHES=$(grep -rnE "(Co-Authored-By: Claude|Generated with Claude|Generated by Claude|Generated by AI)" "$TARGET_DIR" || true)
if [ -n "$AI_MATCHES" ]; then
    echo "ОШИБКА: Найдены ИИ-маркеры в коде:" >&2
    echo "$AI_MATCHES" >&2
    exit 1
fi

# 4. Проверка синтаксиса и контрактов
echo "-> Проверка валидности YAML..."
python3 -c "import yaml; yaml.safe_load(open('$TARGET_DIR/DATA-API.yaml')); yaml.safe_load(open('$TARGET_DIR/api/openapi.yaml')); print('YAML валиден')"

# 5. Инициализация чистого Git-репозитория с одним коммитом
echo "-> Создание чистого Git-репозитория..."
cd "$TARGET_DIR"
git init -b master
git config user.name "Team 105"
git config user.email "team105@max.ru"
git add .
git commit -m "feat: solution release for MAX hackathon track Smart City"

COMMIT_HASH=$(git rev-parse HEAD)
SHORT_HASH=$(git rev-parse --short HEAD)

echo ""
echo "=== Экспорт успешно завершён! ==="
echo "Каталог сдачи: $TARGET_DIR"
echo "Commit hash:   $COMMIT_HASH (короткий: $SHORT_HASH)"
echo "Укажите этот hash в первом слайде презентации и в форме сдачи хакатона."
